apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-cost
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/NixndME/kubecon-demo.git
    targetRevision: main
    path: gitops/platform/chat-cost
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-cost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
